# DankSearch Configuration
# See https://github.com/AvengeMedia/danksearch for documentation

index_path = "/home/akitake/.cache/danksearch/index"
listen_addr = ":43654"
max_file_bytes = 2097152
worker_count = 8
text_extensions = [
  ".txt", ".md", ".go", ".py", ".js", ".ts", ".jsx", ".tsx",
  ".json", ".yaml", ".yml", ".toml", ".html", ".css", ".rs",
  ".c", ".cpp", ".h", ".java", ".rb", ".php", ".sh", ".fxml"
]
index_all_files = true
auto_reindex = false
reindex_interval_hours = 24
max_depth = 0

[[index_paths]]
  path = "/home/akitake"
  max_depth = 6
  exclude_hidden = true
  exclude_dirs = [
    "Arcade", "Code", "Documents", "Music", "Pictures",
    "node_modules", "bower_components", ".npm", ".yarn", "site-packages",
    "__pycache__", ".venv", "venv", ".tox", ".pytest_cache", ".eggs", "dist",
    "build", "out", "bin", "obj", "target", "vendor", ".gradle", ".m2", "bundle",
    ".cache", ".parcel-cache", ".next", ".nuxt", ".serverless", "Library", ".Trash-1000",
    ".postgresql", ".postgres", ".mysql", ".mongodb", ".redis", "pgdata", "pg_data", "go",
    ".cargo", ".pyenv", ".rbenv", ".nvm", ".rustup", ".composer", ".gem", ".idea", ".vscode"
  ]
  extract_exif = true

[[index_paths]]
  path = "/home/akitake/.dotfiles"
  max_depth = 0
  exclude_hidden = false
  exclude_dirs = []
  extract_exif = false

[[index_paths]]
  path = "/mnt/HDD/Cloud"
  max_depth = 0
  exclude_hidden = false
  exclude_dirs = ["Music"]
  extract_exif = true

[[index_paths]]
  path = "/mnt/HDD/Code"
  max_depth = 0
  exclude_hidden = false
  exclude_dirs = [
    ".git",
    "node_modules", "bower_components", ".npm", ".yarn", "site-packages",
    "__pycache__", ".venv", "venv", ".tox", ".pytest_cache", ".eggs", "dist",
    "build", "out", "bin", "obj", "target", "vendor", ".gradle", ".m2", "bundle",
    ".cache", ".parcel-cache", ".next", ".nuxt", ".serverless", "Library", ".Trash-1000",
    ".postgresql", ".postgres", ".mysql", ".mongodb", ".redis", "pgdata", "pg_data", "go",
    ".cargo", ".pyenv", ".rbenv", ".nvm", ".rustup", ".composer", ".gem", ".idea", ".vscode"
  ]
  extract_exif = false

